### ISSUE TITLE
How to fix uses internal aapt2 when merge resources in newer gradle plugin version?

### ISSUE THREAD

**Issue by ISNing** [VcotyQin/TermuxWithGradle#1]
Hi!
I've tried this in Linux Deploy.
And I've successfully built an HelloWorld app by replace some file of Android SDK. I get these file by installing android-sdk package with apt command.

But there's a problem when gradle plugin version newer than 3.0.0. gradle will use it's internal aapt tools when merge resources, but they are built for amd64 platform, it's not working.

Do you have any suggestions with it?
Such as disable it or replace it automatically.

**Comment by VcotyQin** [comment]
Well,Actually there is a way to resolve it.The gradle will download another appt/aapt2 file when your Android gradle version is higher than 3.1.0.So just replace it.
The path of the file is `~/.gradle/caches/modules-2/files-2.1/com.android.tools.build/aapt2`(This path is not necessarily the same as yours.)
Then you'll see a `.jar` file,unziping it,and replacing the appt/app2 file with your aapt/aapt2.

**Comment by ISNing** [comment]
Oh, thanks!
I will have a try :)

Come from Coolapk.

**Comment by VcotyQin** [comment]
py completed![doge]

**Comment by ISNing** [comment]
I found file R.java hasn't generated when building the project...
How to fix it?

**Comment by ISNing** [comment]
@
